# Generated by Django 5.1.7 on 2026-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
