# Generated by Django 5.1.7 on 2026-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiting_threshold',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
