# Generated by Django 6.0.2 on 2026-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_scheduled_booking_scheduled_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_scheduled',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('schedule', 'Schedule')], default='instant', max_length=20),
        ),
    ]
