# Generated by Django 6.0.2 on 2026-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_is_scheduled_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ride_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], default='car', max_length=20),
        ),
    ]
