# Generated by Django 5.1.7 on 2026-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_ride_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
