# Generated by Django 5.1.7 on 2026-03-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehicle_ac_available'),
        ('bookings', '0006_booking_dropoff_booking_pickup'),
        ('reviews', '0001_initial'),
        ('rides', '0006_alter_ride_dropped_time_alter_ride_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerreview',
            name='student',
        ),
        migrations.AddField(
            model_name='passengerreview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_reviews', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='passengerreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_passenger_reviews', to='accounts.rider'),
        ),
        migrations.AddField(
            model_name='passengerreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ridereview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_reviews', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='ridereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_ride_reviews', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='ridereview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reviews', to='bookings.booking')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_vehicle_reviews', to='accounts.student')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reviews', to='rides.ride')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reviews', to='accounts.vehicle')),
            ],
        ),
    ]
