# Generated by Django 5.1.7 on 2026-03-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehicle_ac_available'),
        ('bookings', '0006_booking_dropoff_booking_pickup'),
        ('reviews', '0002_remove_passengerreview_student_and_more'),
        ('rides', '0006_alter_ride_dropped_time_alter_ride_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengerreview',
            old_name='booking',
            new_name='whom_reviewed',
        ),
        migrations.RemoveField(
            model_name='vehiclereview',
            name='booking',
        ),
        migrations.AlterField(
            model_name='passengerreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_passenger_reviews', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='vehiclereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_vehicle_reviews', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_rider_reviews', to='bookings.booking')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews', to='rides.ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews', to='accounts.rider')),
            ],
        ),
        migrations.DeleteModel(
            name='RideReview',
        ),
    ]
