# Generated by Django 5.1.7 on 2026-04-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp_otp_type'),
        ('bookings', '0006_booking_dropoff_booking_pickup'),
        ('reviews', '0005_platformreview'),
        ('rides', '0006_alter_ride_dropped_time_alter_ride_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancel', 'Cancel')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_student_reviews', to='accounts.rider')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reviews', to='rides.ride')),
                ('student_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rider_reviews', to='bookings.booking')),
            ],
        ),
    ]
