# Generated by Django 5.1.7 on 2026-03-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assigned_rider',
        ),
        migrations.AddField(
            model_name='community',
            name='short_name',
            field=models.CharField(default='TEMP', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='employer_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hired_riders', to='accounts.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=20),
        ),
    ]
