# Generated by Django 5.1.7 on 2026-03-01 04:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_assigned_rider_community_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='license_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.rider_license_pic_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.student_id_pic_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_pic_path),
        ),
    ]
