# Generated by Django 5.1.7 on 2026-03-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.CharField(max_length=50),
        ),
    ]
