# Generated by Django 5.1.7 on 2026-03-03 04:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tax_token_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.tax_token_pic_path),
        ),
    ]
