# Generated by Django 6.0.2 on 2026-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ac_available',
            field=models.BooleanField(default=False),
        ),
    ]
