# Generated by Django 6.0.2 on 2026-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehicle_ac_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('forgot_password', 'Forgot Password')], default='signup', max_length=20),
        ),
    ]
