# Generated by Django 5.1.7 on 2026-03-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_rider_alter_ride_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='waiting_threshold',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
