# Generated by Django 5.1.7 on 2026-03-06 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehicle_ac_available'),
        ('rides', '0003_ride_scheduled_start_ride_waiting_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_ride_posts', to='accounts.student'),
        ),
    ]
