# Generated by Django 5.1.7 on 2026-03-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vehicle_ac_available'),
        ('rides', '0004_ride_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='host',
        ),
        migrations.AddField(
            model_name='ride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_rides', to='accounts.student'),
        ),
    ]
