# Generated by Django 5.1.7 on 2026-03-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_host_ride_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dropped_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='dropped_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
