# Generated by Django 6.0.2 on 2026-04-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp_otp_type'),
        ('rides', '0006_alter_ride_dropped_time_alter_ride_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RiderCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_ride_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Bank Transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('due', 'Due'), ('paid', 'Paid'), ('failed', 'Failed')], default='due', max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_commissions', to='accounts.rider')),
                ('rides', models.ManyToManyField(related_name='rider_commissions', to='rides.ride')),
            ],
        ),
    ]
