# Generated by Django 6.0.2 on 2026-04-06 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp_otp_type'),
        ('rides', '0007_ride_commission_rate_ride_total_fare_ridercommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_ride_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('due', 'Due'), ('paid', 'Paid'), ('failed', 'Failed')], default='due', max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_commissions', to='accounts.student')),
                ('rides', models.ManyToManyField(related_name='owner_commissions', to='rides.ride')),
            ],
        ),
        migrations.DeleteModel(
            name='RiderCommission',
        ),
    ]
